apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-loader
  namespace: quay-perf
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
