---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-perf-test-serviceaccount
rules:
- apiGroups: ["extensions", "apps", "batch", "security.openshift.io", "policy"]
  resources: ["deployments", "jobs", "pods", "services", "jobs/status", "podsecuritypolicies", "securitycontextconstraints"]
  verbs: ["use", "get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quay-perf-test-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quay-perf-test-serviceaccount
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    quay-perf-test-component: redis
spec:
  replicas: 1 
  selector:
    matchLabels:
      quay-perf-test-component: redis
  template:
    metadata:
      labels:
        quay-perf-test-component: redis
    spec:
      containers:
      - name: redis-master
        image: registry.access.redhat.com/rhscl/redis-32-rhel7
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    quay-perf-test-component: redis-service
spec:
  ports:
    - port: 6379
  selector:
    quay-perf-test-component: redis
---
apiVersion: batch/v1
kind: Job
metadata:
  name: quay-perf-test-orchestrator
  labels:
    quay-perf-test-component: orchestrator
spec:
  template:
    spec:
      containers:
      - name: python
        image: quay.io/vchalla/quay-load:latest
        securityContext:
          privileged: true
        env:
          - name: QUAY_HOST
            value: mkok-dev.quaydev.org
          - name: QUAY_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: quay-oauth
                key: oauth_token
          - name: QUAY_ORG
            value: 'performance-test'
          - name: ES_HOST
            valueFrom:
              secretKeyRef:
                name: elastic-host
                key: elastic_url
          - name: ES_PORT
            value: '80'
          - name: PYTHONUNBUFFERED
            value: '0'
          - name: ES_INDEX
            value: 'quay'
          - name: PUSH_PULL_IMAGE
            value: 'quay.io/marckok/quay'
          - name: PUSH_PULL_ES_INDEX
            value: 'quay_push_pull'
          - name: PUSH_PULL_NUMBERS
            value: "50"
          - name: TARGET_HIT_SIZE
            value: '1000'
          - name: CONCURRENCY
            value: '10'
          - name: TEST_NAMESPACE
            value: 'performance-test'
          - name: TEST_PHASES
            value: 'LOAD,RUN,DELETE'
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
