kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quay-loader
  namespace: quay-perf
subjects:
- kind: ServiceAccount
  name: default
  namespace: quay-perf
roleRef:
  kind: Role
  name: quay-loader
  apiGroup: rbac.authorization.k8s.io
