---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-vegeta
  namespace: quay-perf
spec:
  parallelism: ${PARALLELISM}
  completions: ${POD_COUNT}
  template:
    spec:
      containers:
      - command:
        - /scripts/run-script.sh
        env:
        - name: QUAY_URL
          value: ${QUAY_URL}
        - name: TOKEN
          value: "${TOKEN}"
        - name: NUM_USERS
          value: "${NUM_USERS}"
        - name: NUM_TAGS
          value: "${NUM_TAGS}"
        image: quay.io/cloud-bulldozer/vegeta:latest
        imagePullPolicy: Always
        name: load
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /scripts
          name: run-script
      volumes:
      - configMap:
          defaultMode: 484
          name: run-script
        name: run-script
      restartPolicy: Never

