---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-vegeta
  namespace: quay-perf
spec:
  parallelism: ${PARALLELISM}
  completions: ${POD_COUNT}
  template:
    spec:
      containers:
      - command:
        - /scripts/run-script.sh
        env:
        - name: QUAY_URL
          value: ${QUAY_URL}
        - name: NUM_USERS
          value: "${NUM_USERS}"
        - name: NUM_TAGS
          value: "${NUM_TAGS}"
        - name: UUID
          value: "${UUID}"
        - name: RATE
          value: "${RATE}"
        - name: DURATION
          value: "${DURATION}"
        - name: ES
          value: "${ES}"
        - name: DB
          value: "${DB}"
        - name: TEST_NAME
          value: "${TEST_NAME}"
        - name: QUAY_VERSION
          value: "${QUAY_VERSION}"
        - name: ES_PORT
          value: "${ES_PORT}"
        image: quay.io/cloud-bulldozer/vegeta:latest
        imagePullPolicy: Always
        name: load
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /scripts
          name: run-script
      volumes:
      - configMap:
          defaultMode: 484
          name: run-script
        name: run-script
      restartPolicy: Never

